table 'Data/Hora Atualização'
	lineageTag: dbca59b1-d619-402b-9154-009f2be6fb10

	measure 'Usuário Logado' = USERPRINCIPALNAME()
		lineageTag: eee1744d-8536-4be9-b6ca-81f293c6be95

	column 'Data da Última Atualização (Sem Tratamento)'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e9dc1b0-97ba-46c8-829a-c1633f9a91c0
		summarizeBy: none
		sourceColumn: Data da Última Atualização (Sem Tratamento)

		variation Variation
			isDefault
			relationship: 61eb2ac7-a4db-44de-ab03-2115c11ab43f
			defaultHierarchy: LocalDateTable_053f928a-42a6-49c2-ae14-6749bef29780.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data da Última Atualização'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ad2fb50-c569-4cc3-8840-fc0c44310de5
		summarizeBy: none
		sourceColumn: Data da Última Atualização

		variation Variation
			isDefault
			relationship: 1fc12575-84c9-41ab-940e-686ba4dd1d8f
			defaultHierarchy: LocalDateTable_3b10c37d-2884-49e8-be7d-201454ffea5d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Remove 3hrs.2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3247e837-2ba6-4338-948f-c9f136cea211
		summarizeBy: none
		sourceColumn: Remove 3hrs.2

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Data/Hora Atualização' = m
		mode: import
		source =
				let
				    Fonte = DateTime.LocalNow(),
				    #"Convertido para Tabela" = #table(1, {{Fonte}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data da Última Atualização"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data da Última Atualização", type datetimezone}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Remove 3hrs", each DateTimeZone.SwitchZone([Data da Última Atualização], -3)),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Table.TransformColumnTypes(#"Personalização Adicionada", {{"Remove 3hrs", type text}}, "pt-BR"), "Remove 3hrs", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Remove 3hrs.1", "Remove 3hrs.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Remove 3hrs.1", type datetime}, {"Remove 3hrs.2", type time}}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Tipo Alterado1",{{"Data da Última Atualização", "Data da Última Atualização (Sem Tratamento)"}, {"Remove 3hrs.1", "Data da Última Atualização"}})
				in
				    #"Colunas Renomeadas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

