table fPonto_Cooperado
	lineageTag: 02eb0a35-0c29-42d1-a54c-c9c25d46db77

	measure 'Soma Hrs Trabalhadas Coop' = SUM(fPonto_Cooperado[horasTrabalhadas])
		formatString: #,0.00
		lineageTag: 6d61259d-979e-4441-949a-b79211fcd47d

		changedProperty = IsHidden

	column idFuncionario
		dataType: int64
		formatString: 0
		lineageTag: 1ed8629b-d03a-4f31-a969-928c0b27e74b
		summarizeBy: none
		sourceColumn: idFuncionario

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column nome
		dataType: string
		lineageTag: e62f0b63-e727-44d1-803a-50e227bbbbaa
		summarizeBy: none
		sourceColumn: nome

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column time
		dataType: string
		lineageTag: 41387631-696f-4789-b2e8-6a2f3a834ca3
		summarizeBy: none
		sourceColumn: time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column setor
		dataType: string
		lineageTag: bccea97f-a992-4930-b157-c36ef342fbb4
		summarizeBy: none
		sourceColumn: setor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		isNullable: false
		formatString: Short Date
		lineageTag: 9f3c4d9b-b7df-4aa8-86f5-3e0275f2851b
		summarizeBy: none
		sourceColumn: data

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column entrada1
		dataType: string
		lineageTag: a869cb8f-e9fb-4a85-974e-911be81fa859
		summarizeBy: none
		sourceColumn: entrada1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column saida1
		dataType: string
		lineageTag: dc29085a-fbeb-4491-b79b-df6768fa4f00
		summarizeBy: none
		sourceColumn: saida1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entrada2
		dataType: string
		lineageTag: 5da8cef2-09ed-4e5a-8bf8-e222b7ac51e8
		summarizeBy: none
		sourceColumn: entrada2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column saida2
		dataType: string
		lineageTag: e2764a95-c799-434f-b063-1ee2a8593eaa
		summarizeBy: none
		sourceColumn: saida2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entrada3
		dataType: string
		lineageTag: 3cd7353a-d918-49c3-989f-9d83a195cd7c
		summarizeBy: none
		sourceColumn: entrada3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column saida3
		dataType: string
		lineageTag: 80398156-6ea0-47ab-89aa-abd97fcb4b84
		summarizeBy: none
		sourceColumn: saida3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column horasTrabalhadas
		dataType: double
		formatString: 0.00
		lineageTag: 5f370981-3194-41ed-9c9f-2a3dd300a737
		summarizeBy: sum
		sourceColumn: horasTrabalhadas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column matricula
		dataType: int64
		formatString: 0
		lineageTag: 7f8d850b-2b40-4500-abff-c976e613e35b
		summarizeBy: none
		sourceColumn: matricula

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column email
		dataType: string
		lineageTag: 604bb9f8-7f9e-49db-8bdd-8f8b22f29ddf
		summarizeBy: none
		sourceColumn: email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition fPonto_Cooperado = m
		mode: import
		source =
				let
				    Fonte = Json.Document(Web.Contents("https://service.sabium.com.br/api_controlehoras/controle-publico/apontamento/cooperado/buscaLista")),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"idFuncionario", "nome", "time", "setor", "data", "entrada1", "saida1", "entrada2", "saida2", "entrada3", "saida3", "horasTrabalhadas", "matricula", "email"}, {"idFuncionario", "nome", "time", "setor", "data", "entrada1", "saida1", "entrada2", "saida2", "entrada3", "saida3", "horasTrabalhadas", "matricula", "email"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Column1 Expandido",{{"idFuncionario", Int64.Type}, {"nome", type text}, {"time", type text}, {"setor", type text}, {"data", type date}, {"entrada1", type any}, {"saida1", type any}, {"entrada2", type any}, {"saida2", type any}, {"entrada3", type any}, {"saida3", type any}, {"horasTrabalhadas", type number}, {"matricula", Int64.Type}, {"email", type text}}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"nome", Text.Proper, type text}, {"time", Text.Proper, type text}, {"setor", Text.Proper, type text}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colocar Cada Palavra Em Maiúscula",{{"data", type date}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

